# Generated by Django 5.0.4 on 2024-11-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('habitat', models.CharField(max_length=200)),
                ('characteristics', models.TextField()),
            ],
        ),
    ]
